<a href="https://colab.research.google.com/github/abhaysingh444/Assignments/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


# the basics

a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [3]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# get dimension
a.ndim
b.ndim

2

In [5]:
# Get shape
a.shape #it tells number of element like rows and columns combined
b.shape #it contains two rows and three cplumns

(2, 3)

In [6]:
# How mch memory our numpy is taking
a.itemsize


2

In [7]:
# Get Type
a.dtype

dtype('int16')

In [8]:
# Get The total size
a.itemsize

2

In [9]:
# Get Total size
a.nbytes

6

In [10]:
#Array creation : Convertion from other Python Structures

listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [11]:
listarray.size

9

In [12]:
listarray.shape

(3, 3)

In [13]:
 zeros=np.zeros((2,5))
 

In [14]:
zeros


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
# Range function

# gives zero to n-1 array

rng=np.arange(15)


In [16]:
rng


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
lspace=np.linspace(1,5,12)

In [18]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [19]:
# above one means ki ye mujhe 1 se lekr 5 tak linearly spaced 12 elements dega
   

In [20]:
#  empty array 


In [21]:
emp=np.empty((4,6))

In [22]:
emp

array([[4.65392747e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [23]:
# purana wale ke size ka ek empty array banayega
emp_like=np.empty_like(lspace)

In [24]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [25]:
# Identity Matrix
ide=np.identity(45)  #gives a 45x45 array


In [26]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [27]:
ide.shape

(45, 45)

In [28]:
arr=np.arange(99)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
# I want to reshape it to some other dimension


In [31]:
arr.reshape(3,33) #also do notice ki multiplication will be of 99 only

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
# ab isko seedha krna hai ,, just like a 1- D array


In [33]:
arr=arr.ravel()

In [34]:
arr.shape

(99,)

In [35]:
# NUMPY AXIS
# remember numpy mein axis 0 se start hoti hai
# agar 1D array hai tohh ek axis hoti hai sirf zero (0) so no logic of axis 1
# 1D array -->1 axis [axis0]
# 2D array --> 2 axis [axis0,axis1]

# row ko axis 1 and column ko axis 0 .... so sum of axis 0 alg hoga and sum of axis 1 alg hoga

In [36]:
x=[[1,2,3],[4,5,6],[7,1,0]]
ar=np.array(x)


In [37]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [38]:
ar.sum(axis=0)

array([12,  8,  9])

In [40]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [ ]:
# Tranpose of a matrix

In [42]:
ar.T  #Transpose

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [44]:
# iterator formation
ar.flat #iterate formation

In [ ]:
# This will Print all the elements in the matrix

In [45]:
for item in ar.flat:
  print(item)

1
2
3
4
5
6
7
1
0


In [47]:
ar.ndim  #Number of dimensions

2

In [49]:
# no. of elements
ar.size

9

In [51]:
ar.nbytes #Total bytes comsumed by array elements

72

In [ ]:
# New 1D array formaton

In [52]:
one=np.array([1,3,4,634,2])

In [54]:
one.argmax()  #when () is used then it shows ki function iuse kiya hai without this () ki attribute hai 
# Maximujm element argmax dega 3 index pe or min 0 pe

3

In [56]:
# Sorting via indexes 
one.argsort()

array([0, 4, 1, 2, 3])

In [58]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [59]:
ar.argmin()

8

In [63]:
# indexes are checked throughout the row like 1 2 3 4

In [64]:
ar.argmax()

6

In [66]:
ar.argmax(axis=0) #column =0 

# isme scne ye hai ki column wise check krega ki first column mein sbse max number konse index pe hai

array([2, 1, 1])

In [68]:
ar.argmax(axis=1)
#isme row consider hongi

array([2, 2, 0])

In [70]:
ar.argsort(axis=1)
#Ye idexing wise sort krega

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [72]:
ar.argsort(axis=0)


array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [75]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [77]:
ar.reshape((9,1))  
#9x1 mein reshape krega

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [78]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [80]:
ar2=np.array([[1,2,1],[4,0,6],[8,1,0]])

In [84]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [82]:
# This is the main benefit where in this two array can be simply added 
# whereas in list this cant be done like this

In [85]:
# extending matrix
[324,34] + [34,546]

[324, 34, 34, 546]

In [87]:
ar * ar2
# yahan pe seedha multiply krdega

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [89]:
np.sqrt(ar)
#square root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [90]:
ar.sum()

29

In [91]:
ar.max()

7

In [92]:
ar.min()

0

In [93]:
# Finding an element in an array

In [94]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [96]:
np.where(ar>5)
# to be noticed ki yaha always index 0 se shuru hoga and ye index hi return krega

(array([1, 2]), array([2, 0]))

In [98]:
type(np.where(ar>5))

tuple

In [101]:
np.count_nonzero(ar)
#It will just count non zero elements

8

In [103]:
np.nonzero(ar)
# it will return tuple like index de dega


(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [106]:
ar[1,2]=0

In [108]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [109]:
import sys

In [110]:
py_ar=[0,4,55,2]

In [111]:
np_ar=np.array(py_ar)

In [113]:
sys.getsizeof(1) *  len(py_ar)
# iska mtlb ki python ki list kitna size legi 1 element ka size in get size of

112

In [115]:
np_ar.itemsize * np_ar.size 
# ek item ka size and multiplied by number of element

32

In [116]:
#See the benefit as this takes so much less space

In [118]:
np_ar.tolist()
# makes numpy array python list


[0, 4, 55, 2]

In [ ]:
# To see more functions go to google and search 
# numpy attributes scipy
# and refer from there as we can copy and paste