<a href="https://colab.research.google.com/github/abhaysingh444/Assignments/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


# the basics

a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [ ]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# get dimension
a.ndim
b.ndim

2

In [ ]:
# Get shape
a.shape #it tells number of element like rows and columns combined
b.shape #it contains two rows and three cplumns

(2, 3)

In [ ]:
# How mch memory our numpy is taking
a.itemsize


2

In [ ]:
# Get Type
a.dtype

dtype('int16')

In [ ]:
# Get The total size
a.itemsize

2

In [ ]:
# Get Total size
a.nbytes

6

In [ ]:
#Array creation : Convertion from other Python Structures

listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [ ]:
listarray.size

9

In [ ]:
listarray.shape

(3, 3)

In [ ]:
 zeros=np.zeros((2,5))
 

In [ ]:
zeros


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# Range function

# gives zero to n-1 array

rng=np.arange(15)


In [ ]:
rng


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
lspace=np.linspace(1,5,12)

In [ ]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [ ]:
# above one means ki ye mujhe 1 se lekr 5 tak linearly spaced 12 elements dega
   

In [ ]:
#  empty array 


In [ ]:
emp=np.empty((4,6))

In [ ]:
emp

array([[0.00000000e+000, 6.76869935e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 5.30276956e+180],
       [6.00736842e-067, 4.95463600e+097, 3.38172554e-057,
        3.41646687e+126, 4.25223142e+180, 7.48543529e+247],
       [2.32363010e+251, 6.11130817e+223, 2.59903818e-144,
        1.74383398e-076, 4.99029685e+174, 4.47112908e-090],
       [3.53948292e-061, 2.59027861e-144, 1.16442250e-028,
        9.44872517e-143, 6.17582057e-322, 0.00000000e+000]])

In [ ]:
# purana wale ke size ka ek empty array banayega
emp_like=np.empty_like(lspace)

In [ ]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [ ]:
# Identity Matrix
ide=np.identity(45)  #gives a 45x45 array


In [ ]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
ide.shape

(45, 45)

In [ ]:
arr=np.arange(99)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
# I want to reshape it to some other dimension


In [ ]:
arr.reshape(3,33) #also do notice ki multiplication will be of 99 only

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
# ab isko seedha krna hai ,, just like a 1- D array


In [ ]:
arr=arr.ravel()

In [ ]:
arr.shape

(99,)

In [ ]:
# NUMPY AXIS
# remember numpy mein axis 0 se start hoti hai
# agar 1D array hai tohh ek axis hoti hai sirf zero (0) so no logic of axis 1
# 1D array -->1 axis [axis0]
# 2D array --> 2 axis [axis0,axis1]

# row ko axis 1 and column ko axis 0 .... so sum of axis 0 alg hoga and sum of axis 1 alg hoga

In [ ]:
x=[[1,2,3],[4,5,6],[7,1,0]]
ar=np.array(x)


In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
ar.sum(axis=0)

array([12,  8,  9])